---
Title: Docker Compose
Owner: Silver Surfer
Last_Verified: 2025-09-01
Version: v1.0.0
Risk: Medium
Tags: ['docker']
---
version: '3.9'
services:
  web:
    image: python:3.11-slim
    command: python -m http.server 8000
    ports: ['8000:8000']
