name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compose up
        run: make up

      - name: Run smoke tests
        run: make test

      - name: Compose down
        if: always()
        run: make down
