name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compose up
        run: docker compose -f 05_Replica/infra/docker-compose.yml up -d

      - name: Run smoke tests
        run: bash 05_Replica/tests/smoke_test.sh

      - name: Compose down
        if: always()
        run: docker compose -f 05_Replica/infra/docker-compose.yml down
